from building import *

cwd     = GetCurrentDir()
path = [cwd]
src     = Glob('src/*.c')
src += Glob('src/nes_mapper/*.c')

path += [cwd + '/inc']

group = DefineGroup('nes', src, depend = ['BSP_USING_NES_C'], CPPPATH = path)

Return('group')
